In [2]:
import pandas as pd

In [3]:
#Load CSV files
df_c = pd.read_csv("customers.csv")
df_da = pd.read_csv("delivery_addresses.csv")
df_ol = pd.read_csv("order_line.csv")
df_il = pd.read_csv("invoice_line.csv")
df_d = pd.read_csv("deliveries.csv")

In [6]:
df_c.head()

,Customer ID,Name,Customer type,Registration no,VAT no,City,Country,Registration date,Updated date
0,CUST-962512,Nexbit Industrie GmbH,business,DE990078456,DE99007845,Cologne,DE,2012-08-18,2014-09-01
1,CUST-252537,Drelnex AB,business,SE556882345601,SE 556882345601,Gothenburg,SE,2022-01-31,2022-08-05
2,CUST-684995,Quordan Electronica BV,business,NL441122334B01,NL441122334B01,Amsterdam,NL,2014-04-20,2015-12-29
3,CUST-937933,Veltron Technik GmbH,business,DE312445678,DE31244567,Berlin,DE,2021-03-25,2021-04-28
4,CUST-352175,Drexon Elektronik GmbH,business,DE778856234,DE77885623,Stuttgart,DE,2018-09-19,2020-11-06

In [4]:
df = df_ol.merge(
    df_il,
    on=["order_id", "product_id"],
    how="outer",
    suffixes=("_order", "_invoice")
)

In [5]:
df["quantity_diff"] = df["quantity_invoice"] - df["quantity_order"]

In [6]:
df["quantity_issue"] = df["quantity_diff"].apply(
    lambda x: "OK" if x == 0 else ("Over-invoiced" if x > 0 else "Under-invoiced")
)

In [7]:
df[df["quantity_issue"] != "OK"]

,order_line_id,order_id,order_date,customer_id,delivery_place_id,product_id,product_description_order,product_type,quantity_order,uom_order,...,currency_invoice,line_amount,vat_rate,vat_amount,total_amount,invoice_status,invoice_ref,vat_category_code,quantity_diff,quantity_issue
2,OL-003,ORD-2026-137589,2026-12-19,CUST-741029,DEL-74815247,PROD-564738,Fomex Cat8 Patch Cable 3m,Product,91,m,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
3,OL-002,ORD-2026-137589,19/12/2026,CUST-741029,DEL-74815247,PROD-639182,Blipcore Wireless Adapter AC1200,Product,63,pcs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
4,OL-001,ORD-2026-137589,2026-12-19,CUST-741029,DEL-74815247,PROD-847263,Nexboard Mechanical Keyboard TKL,Product,4,pcs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
8,OL-001,ORD-2026-289444,2026-12-11,CUST-349362,DEL-57745602,PROD-564738,Fomex Cat8 Patch Cable 3m,Product,76,m,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
9,OL-002,ORD-2026-289444,2026-12-11,CUST-349362,DEL-57745602,PROD-583047,Veltric UPS 600VA Tower,Product,14,pcs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
22,OL-002,ORD-2026-546766,2026-12-28,CUST-406524,DEL-95826704,PROD-483921,Zoltrix 4K Display Module 27in,Product,16,pcs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
23,OL-001,ORD-2026-546766,2026-12-28,CUST-406524,DEL-95826704,PROD-738291,Quorvex 2TB NVMe SSD M.2,Product,2,pcs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
26,OL-002,ORD-2026-723470,16/12/2026,CUST-599370,DEL-50594568,PROD-461829,Plonex Webcam 1080p Pro,Product,6,pcs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
27,OL-001,ORD-2026-723470,2026-12-16,CUST-599370,DEL-50594568,PROD-639182,Blipcore Wireless Adapter AC1200,Product,96,pcs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
31,OL-001,ORD-2026-918738,2026-12-15,CUST-682893,DEL-29977543,PROD-271045,Vantec USB-C Hub 9-port,Product,71,pcs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
32,OL-002,ORD-2026-918738,2026-12-15T17:31:00,CUST-682893,DEL-29977543,PROD-461829,Plonex Webcam 1080p Pro,Product,35,pcs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
64,OL-003,ORD-2027-359081,2027-01-24,CUST-682893,DEL-29977543,PROD-192837,Droxel 65W GaN Charger,Product,39,pcs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
65,OL-001,ORD-2027-359081,2027-01-24,CUST-682893,DEL-29977543,PROD-483921,Zoltrix 4K Display Module 27in,Product,62,pcs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
66,OL-002,ORD-2027-359081,2027-01-24,CUST-682893,DEL-29977543,PROD-564738,Fomex Cat8 Patch Cable 3m,Product,20,m,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
71,OL-002,ORD-2027-428001,26/01/2027,CUST-962512,DEL-73389540,PROD-483921,Zoltrix 4K Display Module 27in,Product,17,pcs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
72,OL-001,ORD-2027-428001,2027-01-26,CUST-962512,DEL-73389540,PROD-639182,Blipcore Wireless Adapter AC1200,Product,23,pcs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
97,OL-001,ORD-2027-731065,2027-01-17T16:19:00,CUST-406524,DEL-95826704,PROD-639182,Blipcore Wireless Adapter AC1200,Product,72,pcs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
98,OL-002,ORD-2027-731065,2027-01-17,CUST-406524,DEL-95826704,PROD-738291,Quorvex 2TB NVMe SSD M.2,Product,46,pcs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
101,OL-001,ORD-2027-807937,2027-02-16,CUST-406524,DEL-95826704,PROD-583047,Veltric UPS 600VA Tower,Product,48,pcs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
102,OL-002,ORD-2027-807937,2027-02-16,CUST-406524,DEL-95826704,PROD-738291,Quorvex 2TB NVMe SSD M.2,Product,1,pcs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
114,OL-002,ORD-2027-931472,20/01/2027,CUST-962512,DEL-73389540,PROD-461829,Plonex Webcam 1080p Pro,Product,94,pcs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
115,OL-001,ORD-2027-931472,2027-01-20,CUST-962512,DEL-73389540,PROD-583047,Veltric UPS 600VA Tower,Product,41,pcs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
120,OL-001,ORD-2027-945460,2027-01-16,CUST-962512,DEL-73389540,PROD-461829,Plonex Webcam 1080p Pro,Product,56,pcs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
121,OL-002,ORD-2027-945460,2027-01-16,CUST-962512,DEL-73389540,PROD-583047,Veltric UPS 600VA Tower,Product,40,pcs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced
122,OL-003,ORD-2027-945460,2027-01-16T15:20:00,CUST-962512,DEL-73389540,PROD-639182,Blipcore Wireless Adapter AC1200,Product,83,pcs,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Under-invoiced

In [8]:
df["quantity_issue"].value_counts()

quantity_issue
OK                103
Under-invoiced     25
Name: count, dtype: int64