In [1]:
import pandas as pd

In [16]:
sales_rep = pd.read_csv("SalesRep.csv", sep=";")

In [17]:
sales_rep_clean = sales_rep.drop_duplicates()

In [18]:
sales_rep

,Manager,Manager Number,Sales Rep Number,Sales Rep Name,Sales Rep Name2,Path
0,Amanda Honda,104,103,Amalia Craig,Amalia Craig,Amanda Honda-Amalia Craig
1,Amanda Honda,104,176,Sheila Hein,Sheila Hein,Amanda Honda-Sheila Hein
2,Amanda Honda,104,104,Amanda Honda,-,Amanda Honda
3,Amanda Honda,104,112,Cart Lynch,Cart Lynch,Amanda Honda-Cart Lynch
4,Amanda Honda,104,103,Amalia Craig,Amalia Craig,Amanda Honda-Amalia Craig
...,...,...,...,...,...,...
29067,William Fisher,185,147,Kim Williams,William Fisher,Brenda Gibson-William Fisher-Kim Williams
29068,William Fisher,185,129,Edward Smith,William Fisher,Brenda Gibson-William Fisher-Edward Smith
29069,William Fisher,185,147,Kim Williams,William Fisher,Brenda Gibson-William Fisher-Kim Williams
29070,William Fisher,185,129,Edward Smith,William Fisher,Brenda Gibson-William Fisher-Edward Smith
29071,William Fisher,185,129,Edward Smith,William Fisher,Brenda Gibson-William Fisher-Edward Smith

In [15]:
sales_rep_clean

,Manager,Manager Number,Sales Rep Number,Sales Rep Name,Sales Rep Name2,Path
0,Amanda Honda,104,103,Amalia Craig,Amalia Craig,Amanda Honda-Amalia Craig
1,Amanda Honda,104,176,Sheila Hein,Sheila Hein,Amanda Honda-Sheila Hein
2,Amanda Honda,104,104,Amanda Honda,-,Amanda Honda
3,Amanda Honda,104,112,Cart Lynch,Cart Lynch,Amanda Honda-Cart Lynch
21,Amanda Honda,104,159,Molly McKenzie,Molly McKenzie,Amanda Honda-Molly McKenzie
...,...,...,...,...,...,...
26827,Stewart Wind,181,111,Carolyn Halmon,Carolyn Halmon,Stewart Wind-Carolyn Halmon
26829,Stewart Wind,181,181,Stewart Wind,-,Stewart Wind
28414,Viginia Mountain,184,127,Edward Laychak,Viginia Mountain,John Greg-Viginia Mountain-Edward Laychak
28826,William Fisher,185,129,Edward Smith,William Fisher,Brenda Gibson-William Fisher-Edward Smith
28829,William Fisher,185,147,Kim Williams,William Fisher,Brenda Gibson-William Fisher-Kim Williams

In [19]:
sales_rep_clean.to_csv("sales_rep_clean.csv", sep=";", index=False)